vim.g.mapleader = ' '

vim.opt.encoding = "utf-8"
vim.opt.number = true
vim.opt.wrap = true
vim.opt.mouse = "a"
vim.opt.relativenumber=true
vim.opt.backup = false
vim.opt.clipboard = "unnamedplus"
vim.opt.hlsearch = true
vim.opt.incsearch = true
vim.opt.ignorecase = true
vim.opt.smartcase = true
vim.opt.showmode = true
vim.opt.showcmd = true
vim.opt.showmatch = true
vim.opt.splitright = true
vim.opt.splitbelow = true
vim.opt.swapfile = false
vim.opt.smartindent = true
